name: $(Date:yyyyMMdd).$(Rev:r).$(Build.BuildId)

stages:
  - stage: Stage
    jobs:
      - job: Staging
        steps:
          - bash: |
              arry=(buildVar swapVar job_test)
              for x in ${arry[@]};do
                echo "##vso[task.setvariable variable=$x;isOutput=true]true"
              done
            env:
              buildVar: 'buildVar'
              swapVar: 'swapVar'
            name: printvar

  - stage: Swap
    dependsOn: Stage
    variables:
      - template: ../templates/variables.yml
    jobs:
      - template: ../templates/test.yml
      - job: Build
        displayName: "Docker build and push"
        steps:
          - script: echo $(myVarfromStage)
        condition: and(succeeded(), eq(variables.swapVar, true))

  - stage: Build
    dependsOn: Stage
    displayName: Pre build stage
    variables:
      buildVar: $[ stageDependencies.Stage.Staging.outputs['printvar.buildVar'] ]
    jobs:
    - job: Deploy
      steps:
        - template: ../templates/echo_list.yml
      condition: and(succeeded(), eq(variables.buildVar, true))