name: $(Date:yyyyMMdd).$(Rev:r).$(Build.BuildId)

stages:
  - stage: Stage
    jobs:
      - job: Staging
        steps:
          - bash: echo "##vso[task.setvariable variable=myStageOutputVar;isOutput=true]$myVar"
            env:
              myVar: 'this is a stage output var'
            name: printvar

  - stage: Swap
    dependsOn: Stage
    variables:
      myVarfromStage: $[ stageDependencies.Stage.Staging.outputs['printvar.myStageOutputVar'] ]
    jobs:
      - job: Build
        steps:
          - script: echo $(myVarfromStage)

  - stage: PreBuild
    displayName: Pre build stage
    jobs:
    - job: Build
      steps:
        - template: ../templates/echo_list.yml

  - stage: Build
    displayName: Build stage
    dependsOn: PreBuild
    variables:
      list: $[ stageDependencies.PreBuild.Build.outputs['echo.MODULES_IMPACTED'] ]
    jobs:
      - template: ../templates/job1.yaml
        parameters:
          jobs: $(list)