name: $(Date:yyyyMMdd).$(Rev:r).$(Build.BuildId)

stages:
  - stage: PreBuild
    displayName: Pre build stage
    jobs:
    - job: Build
      steps:
        - template: ../templates/echo_list.yml

  - template: ../templates/stageBuild.yml
    parameters:
      list: $[ dependencies.PreBuild.echo.outputs['passOutput.MODULES_IMPACTED'] ]
