name: $(Date:yyyyMMdd).$(Rev:r).$(Build.BuildId)

stages:
  - stage: Stage
    jobs:
      - job: Staging
        steps:
          - bash: |
              echo "##vso[task.setvariable variable=$buildVar;isOutput=true]$buildVar"
              echo "##vso[task.setvariable variable=$swapVar;isOutput=true]TRUE"
              echo "##vso[task.setvariable variable=job_test;isOutput=true]TRUE"
            env:
              buildVar: 'buildVar'
              swapVar: 'swapVar'
            name: printvar

  - stage: Swap
    dependsOn: Stage
    variables:
      - template: ../templates/variables.yml
    jobs:
      - ${{ if eq(1, 1) }}:
        - template: ../templates/test.yml
      - job: Build
        displayName: "Docker build and push"
        steps:
          - script: echo $(myVarfromStage)
        condition: and(succeeded(), eq(variables.job_test, 'TRUE'))

  - stage: Build
    dependsOn: Stage
    displayName: Pre build stage
    variables:
      buildVar: $[ stageDependencies.Stage.Staging.outputs['printvar.buildVar'] ]
    jobs:
    - job: Build
      steps:
        - template: ../templates/echo_list.yml
      condition: and(succeeded(), eq(variables.buildVar, 'buildVar'))