name: $(Date:yyyyMMdd).$(Rev:r).$(Build.BuildId)

stages:
  - stage: Stage
    jobs:
      - job: Staging
        steps:
          - bash: echo "##vso[task.setvariable variable=myStageOutputVar;isOutput=true]$myVar"
            env:
              myVar: 'this'
            name: printvar

  - stage: Swap
    dependsOn: Stage
    variables:
      myVarfromStage: $[ stageDependencies.Stage.Staging.outputs['printvar.myStageOutputVar'] ]
    jobs:
      - job: Build
        steps:
          - script: echo $(myVarfromStage)

  - stage: PreBuild
    dependsOn: Stage
    displayName: Pre build stage
    variables:
      myVarfromStage: $[ stageDependencies.Stage.Staging.outputs['printvar.myStageOutputVar'] ]
    jobs:
    - job: Build
      steps:
        - template: ../templates/echo_list.yml
      condition: and(succeeded(), eq(variables.myVarfromStage, 'this'))