name: $(Date:yyyyMMdd).$(Rev:r).$(Build.BuildId)

stages:
  - stage: Stage
    jobs:
      - job: Staging
        steps:
          - bash: |
              echo "##vso[task.setvariable variable=$buildVar;isOutput=true]$buildVar"
              echo "##vso[task.setvariable variable=$swapVar;isOutput=true]$swapVar"
            env:
              buildVar: 'buildVar'
              swapVar: 'null'
            name: printvar

  - stage: Swap
    dependsOn: Stage
    variables:
      swapVar: $[ stageDependencies.Stage.Staging.outputs['printvar.swapVar'] ]
    jobs:
      - job: Build
        displayName: "Docker build and push"
        steps:
          - script: echo $(myVarfromStage)
        condition: and(succeeded(), eq(variables.swapVar, 'swapVar'))

  - stage: Build
    dependsOn: Stage
    displayName: Pre build stage
    variables:
      buildVar: $[ stageDependencies.Stage.Staging.outputs['printvar.buildVar'] ]
    jobs:
    - job: Build
      steps:
        - template: ../templates/echo_list.yml
      condition: and(succeeded(), eq(variables.buildVar, 'buildVar'))